language: node_js
cache:
  directories:
    - node_modules
braches:
  only:
    - master
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
services:
  - mongodb
before_script:
  - npm prune
script:
  - npm run test:single
  - nptm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
